In [ ]:
import numpy as np

In [ ]:
y=np.array([1,2,3])

In [ ]:
x=[1,2,3]

In [ ]:
type(x)

list

In [ ]:
type(y)

numpy.ndarray

In [ ]:
y/2

array([0.5, 1. , 1.5])

In [ ]:
y=np.array([1,2,1,1])

In [ ]:
type(y[0]),type(y[1]),type(y[2]),type(y[3])

(numpy.int64, numpy.int64, numpy.int64, numpy.int64)

In [ ]:
np.random.randint(0,7)

0

In [ ]:
np.random.randint(0,7,(3,3))

array([[6, 1, 3],
       [6, 2, 4],
       [3, 1, 5]])

In [ ]:
x=np.random.randint(0,10,(3,3))
y=np.random.randint(0,10,(3,3))

In [ ]:
x

array([[7, 1, 0],
       [7, 5, 8],
       [9, 5, 9]])

In [ ]:
y

array([[3, 6, 7],
       [6, 9, 1],
       [2, 3, 7]])

In [ ]:
np.add(x,y)

array([[10,  7,  7],
       [13, 14,  9],
       [11,  8, 16]])

array([[10,  7,  7],
       [13, 14,  9],
       [11,  8, 16]])

In [ ]:
np.random.rand(3,3)

array([[0.02222452, 0.33025012, 0.81301332],
       [0.87044292, 0.29893017, 0.83624207],
       [0.95361509, 0.63004427, 0.69062501]])

In [ ]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])