In [ ]:
import numpy as np

In [ ]:
data=np.random.randint(0,10,(3,3))

In [ ]:
data

array([[4, 2, 9],
       [4, 8, 4],
       [0, 5, 9]])

In [ ]:
data.sum()

np.int64(45)

In [ ]:
data.sum(axis=0)

array([ 8, 15, 22])

In [ ]:
data.sum(axis=1)

array([15, 16, 14])

In [ ]:
data.max()

np.int64(9)

In [ ]:
data.max(axis=0)

array([4, 8, 9])

In [ ]:
data.max(axis=1)

array([9, 8, 9])

In [ ]:
import numpy as np



In [ ]:
data=np.random.randint(0,10,5)

In [ ]:
data

array([8, 7, 2, 9, 6])

In [ ]:
data+7

array([15, 14,  9, 16, 13])

In [ ]:
x=np.random.randint(0,10,(4,3))


In [ ]:
x

array([[6, 7, 2],
       [8, 9, 5],
       [3, 9, 7],
       [7, 9, 8]])

In [ ]:
y=np.random.randint(0,10,(1,3))

In [ ]:
y

array([[6, 5, 7]])

In [ ]:
x+y

array([[12, 12,  9],
       [14, 14, 12],
       [ 9, 14, 14],
       [13, 14, 15]])

In [ ]:
data=np.random.randint(0,10,5)

In [ ]:
data

array([5, 0, 2, 7, 1])

In [ ]:
data.cumsum()

array([ 5,  5,  7, 14, 15])

In [ ]:
data.cumprod()

array([5, 0, 0, 0, 0])

In [ ]:
a=np.random.choice([1,2,3,5,7],size=3)
a

array([7, 2, 2])